name: Exercício 2 - CI corrigido

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Criar o .env a partir do .env.example
        run: cp .env.example .env

      - name: Subir o ambiente
        run: docker compose up -d --build

      - name: Derrubar o ambiente sempre
        if: always()
        run: docker compose down -v


  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Build
        run: docker build -t biblioteca-api .
